### ISSUE TITLE
No such module 'IperfSwift'

### ISSUE THREAD

**Issue by LeoGui** [igorskh/iperf-swift#10]
Hi,

I use Swift 5 in project, I don't know if it can be a problem. But, I cannot use this library. The module is correctly imported because when I try  :

var iperfRunner: IperfRunner?

Xcode suggests me to import IperfSwift but I can't build after that.

**Comment by igorskh** [comment]
Hi @LeoGui,

Could you provide the build error you are getting?

**Comment by LeoGui** [comment]
![Capture d’écran 2024-07-17 à 13 46 00](https://github.com/user-attachments/assets/63a0659e-0253-43ce-935e-99a90100ef73)
![Capture d’écran 2024-07-17 à 13 46 36](https://github.com/user-attachments/assets/a5c6f54e-b7e3-4a55-a8aa-b02b3db62689)

As you can see the module is correctly imported ...

**Comment by igorskh** [comment]
Can you try running this two commands? I also encountered this error, this seemed to resolve it.

<img width="665" alt="image" src="https://github.com/user-attachments/assets/5944aa6a-767b-48d6-adc3-78151e0d5d51">

**Comment by LeoGui** [comment]
It doesn't work...

**Comment by igorskh** [comment]
I've just created a clean iOS project in Xcode 15 and imported this package, do you have it both in package dependencies and in the targets under "Frameworks, Libraries and Embedded Content"?
What kind of project type did you create?

<img width="795" alt="image" src="https://github.com/user-attachments/assets/c3b709f6-b9a4-45fa-8a05-57465f13d527">

![image](https://github.com/user-attachments/assets/c7e2bed0-9a63-4051-8dfe-ed691ad2179e)

**Comment by LeoGui** [comment]
Oh, it was that, thanks a lot !!

**Comment by LeoGui** [comment]
I saw in previous comment that someone speaks about bidirectional. Do you think you will integrate it or the library is closed ?

**Comment by igorskh** [comment]
Glad I could help.

I'll have a look into #9. I didn't have to time to work on it. I see that iPerf3 has `--bidir` option, maybe it'll be not so complicated to integrate.

I'm closing this issue since it's resolved.
